from django.urls import path, include
from . import views, maviews


urlpatterns = [
    path('', views.myAccount),
    # path('dashboard/', views.myAccount, name='dashboard'),
    path('user-signup/', views.user_signup, name='user_signup'),
    # # path('registerVendor/', views.registerVendor, name='registerVendor'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('myAccount/', views.myAccount, name='myAccount'),
    path('dashboard/', views.myDashboard, name='myDashboard'),
    # # path('vendorDashboard/', views.vendorDashboard, name='vendorDashboard'),
    # # path('custDashboard/', views.custDashboard, name='custDashboard'),

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),

    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('add-services/', maviews.add_services, name='add_services'),
    path('services-list/', maviews.maservices_list, name='maservices_list'),
    path('edit-services/<int:pk>/', maviews.edit_services, name='edit_services'),
    path('delete-services/<int:pk>/', maviews.delete_services, name='delete_services'),
    path('add-services-detail/', maviews.add_services_detail, name='add_services_detail'),
    path('edit-services-detail/<int:pk>/', maviews.edit_services_detail, name='edit_services_detail'),
    path('services-detail-list/', maviews.maservices_detail_list, name='maservices_detail_list'),
    path('delete-services-detail/<int:pk>/', maviews.delete_services_detail, name='delete_services_detail'),
    # path('add-factsheet/', maviews.add_factsheet, name='add_factsheet'),
    path('country/', maviews.add_country, name='add_country'),
    path('edit_country/<int:pk>/', maviews.edit_country, name='edit_country'),
    path('delete-country/<int:pk>/', maviews.delete_country, name='delete_country'),
    path('state/', maviews.add_state, name='add_state'),
    path('edit-state/<int:pk>/', maviews.edit_state, name='edit_state'),
    path('delete-state/<int:pk>/', maviews.delete_state, name='delete_state'),
    path('city/', maviews.add_city, name='add_city'),
    path('edit-city/<int:pk>/', maviews.edit_city, name='edit_city'),
    path('delete-city/<int:pk>/', maviews.delete_city, name='delete_city'),
    path('sector/', maviews.add_sector, name='add_sector'),
    path('edit-sector/<int:pk>/', maviews.edit_sector, name='edit_sector'),
    path('delete-sector/<int:pk>/', maviews.delete_sector, name='delete_sector'),
    path('add-company/', maviews.add_company, name='add_company'),
    path('company-list/', maviews.company_list, name='company_list'),
    path('edit-company/<int:pk>/', maviews.edit_company, name='edit_company'),
    path('delete-company/<int:pk>/', maviews.delete_company, name='delete_company'),
    path('jobtype/', maviews.add_jobtype, name='add_jobtype'),
    path('edit-jobtype/<int:pk>/', maviews.edit_jobtype, name='edit_jobtype'),
    path('delete-jobtype/<int:pk>/', maviews.delete_jobtype, name='delete_jobtype'),
    path('workmode/', maviews.add_workmode, name='add_workmode'),
    path('edit-workmode/<int:pk>/', maviews.edit_workmode, name='edit_workmode'),
    path('delete-workmode/<int:pk>/', maviews.delete_workmode, name='delete_workmode'),
    path('jobcategory/', maviews.add_jobcategory, name='add_jobcategory'),
    path('edit-jobcategory/<int:pk>/', maviews.edit_jobcategory, name='edit_jobcategory'),
    path('delete-jobcategory/<int:pk>/', maviews.delete_jobcategory, name='delete_jobcategory'),
    path('jobrole/', maviews.add_jobrole, name='add_jobrole'),
    path('edit-jobrole/<int:pk>/', maviews.edit_jobrole, name='edit_jobrole'),
    path('delete-jobrole/<int:pk>/', maviews.delete_jobrole, name='delete_jobrole'),
    path('jobskill/', maviews.add_skill, name='add_skill'),
    path('edit-skill/<int:pk>/', maviews.edit_skill, name='edit_skill'),
    path('delete-skill/<int:pk>/', maviews.delete_skill, name='delete_skill'),
    path('education/', maviews.add_education, name='add_education'),
    path('edit-education/<int:pk>/', maviews.edit_education, name='edit_education'),
    path('delete-education/<int:pk>/', maviews.delete_education, name='delete_education'),
    path('experience/', maviews.add_experience, name='add_experience'),
    path('edit-experience/<int:pk>/', maviews.edit_experience, name='edit_experience'),
    path('delete-experience/<int:pk>/', maviews.delete_experience, name='delete_experience'),
    path('position/', maviews.add_position, name='add_position'),
    path('edit-position/<int:pk>/', maviews.edit_position, name='edit_position'),
    path('delete-position/<int:pk>/', maviews.delete_position, name='delete_position'),
    path('edit-about/', maviews.edit_about, name='edit_about'),
    path('edit-specialty/', maviews.edit_specialty, name='edit_specialty'),
    path('add-team/', maviews.add_team, name='add_team'),
    path('team-list/', maviews.team_list, name='team_list'),
    path('edit-team/<int:pk>/', maviews.edit_team, name='edit_team'),
    path('delete-team/<int:pk>/', maviews.delete_team, name='delete_team'),
    path('add-testimonial/', maviews.add_testimonial, name='add_testimonial'),
    path('testimonial/', maviews.testimonial_list, name='testimonial_list'),
    path('edit-testimonial/<int:pk>/', maviews.edit_testimonial, name='edit_testimonial'),
    path('delete-testimonial/<int:pk>/', maviews.delete_testimonial, name='delete_testimonial'),
    path('add-client/', maviews.add_client, name='add_client'),
    path('client/', maviews.client_list, name='client_list'),
    path('edit-client/<int:pk>/', maviews.edit_client, name='edit_client'),
    path('delete-client/<int:pk>/', maviews.delete_client, name='delete_client'),
    path('edit-banner/', maviews.edit_banner, name='edit_banner'),
    path('edit-home/', maviews.edit_home, name='edit_home'),
    path('knowus/', maviews.edit_knowus, name='edit_knowus'),
    path('overview/', maviews.edit_overview, name='edit_overview'),
    path('counter/', maviews.edit_counter, name='edit_counter'),
    path('edit-contact/', maviews.edit_contact, name='edit_contact'),
    path('add-category/', maviews.add_category, name='add_category'),
    path('category/', maviews.category_list, name='category_list'),
    path('edit-category/<int:pk>/', maviews.edit_category, name='edit_category'),
    path('delete-category/<int:pk>/', maviews.delete_category, name='delete_category'),
    path('add-post/', maviews.add_post, name='add_post'),
    path('posts/', maviews.post_list, name='post_list'),
    path('edit-post/<int:pk>/', maviews.edit_post, name='edit_post'),
    path('delete-post/<int:pk>/', maviews.delete_post, name='delete_post'),
    
    path('add-author/', maviews.add_author, name='add_author'),
    path('authors/', maviews.author_list, name='author_list'),
    path('edit-author/<int:pk>/', maviews.edit_author, name='edit_author'),
    path('delete-author/<int:pk>/', maviews.delete_author, name='delete_author'),
    
    path('add-jobpost/', maviews.add_jobpost, name='add_jobpost'),
    path('edit-jobpost/<int:pk>/', maviews.edit_jobpost, name='edit_jobpost'),
    path('job-list/', maviews.job_list, name='job_list'),
    path('delete-jobpost/<int:pk>/', maviews.delete_jobpost, name='delete_jobpost'),
    path('applicant-list/', maviews.applicant_list, name='applicant_list'),
    path('delete-applicant/<int:pk>/', maviews.delete_applicant, name='delete_applicant'),
    path('applicant-detail/<int:pk>/', maviews.myapplicant_detail, name='myapplicant_detail'),

    path('get_states/', maviews.get_states, name='get_states'),
    path('get_cities/', maviews.get_cities, name='get_cities'),
    path('get-job-categories/', maviews.get_job_categories, name='get_job_categories'),
    path('edit-general/', maviews.edit_general, name='edit_general'),
    path('edit-bgbanner/', maviews.edit_bgbanner, name='edit_bgbanner'),
    path('emailsetup/', maviews.emailsetup, name='emailsetup'),
    path('enquiry/', maviews.enquiry_list, name='enquiry_list'),
    path('enquiry-detail/<int:pk>', maviews.enquiry_detail, name='enquiry_detail'),
    path('delete-enquiry/<int:pk>/', maviews.delete_enquiry, name='delete_enquiry'),
    path('feedback/', maviews.feedback_list, name='feedback_list'),
    path('feedback-detail/<int:pk>', maviews.feedback_detail, name='feedback_detail'),
    path('delete-feedback/<int:pk>/', maviews.delete_feedback, name='delete_feedback'),

]