services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=advertsneak_epitome  
      - DATABASE_USER=advertsneak_user  # Changed from root
      - DATABASE_PASSWORD=password123      
      - DATABASE_HOST=db                  
      - DATABASE_PORT=3306

    depends_on:
      - db

  db:
    image: mysql:8.0 
    environment:
      - MYSQL_DATABASE=advertsneak_epitome
      - MYSQL_USER=advertsneak_user       # New user
      - MYSQL_PASSWORD=password123         
      - MYSQL_ROOT_PASSWORD=password123 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: