# Generated by Django 4.0.3 on 2025-02-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bookinguser_consultant_event_booking_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='consultants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingUser',
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
