# Generated by Django 5.1.6 on 2025-02-25 17:16

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='city/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('country_pic', models.ImageField(blank=True, null=True, upload_to='country/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(default='Bachelor Degree', max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Less than a year', max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Devops', max_length=100)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Job_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Full Stack Developer', max_length=100)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Full time', max_length=100)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(default='IT', max_length=250)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Work_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Remote', max_length=100)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='work/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d/')),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.country')),
                ('sector', models.ManyToManyField(to='jobsapp.sector')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=600, unique=True)),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, max_length=300)),
                ('job_location', models.CharField(max_length=250)),
                ('salary', models.CharField(blank=True, max_length=250)),
                ('website_url', models.URLField(blank=True, max_length=100)),
                ('number_of_job', models.PositiveIntegerField(blank=True, null=True)),
                ('last_date', models.DateTimeField()),
                ('filled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsapp.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.company')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsapp.country')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.education')),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.experience')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.job_category')),
                ('Job_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.job_role')),
                ('job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.job_type')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fullstack', max_length=255)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.job')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=500)),
                ('job_url', models.SlugField(blank=True, max_length=700)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('applicant_phone', models.CharField(max_length=16)),
                ('qualification', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=300)),
                ('is_relocated', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100)),
                ('applicant_country', models.CharField(max_length=15)),
                ('applicant_state', models.CharField(max_length=15)),
                ('applicant_city', models.CharField(max_length=100)),
                ('applicant_address', models.CharField(max_length=250)),
                ('employee_type', models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], max_length=100)),
                ('last_company_name', models.CharField(blank=True, max_length=250)),
                ('last_company_designation', models.CharField(blank=True, max_length=250)),
                ('current_ctc', models.CharField(blank=True, max_length=150)),
                ('last_ctc', models.CharField(blank=True, max_length=150)),
                ('applicant_location', models.CharField(max_length=250)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='doc')),
                ('user_id', models.IntegerField(blank=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('working_experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.experience')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobsapp.job')),
                ('applicant_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.position')),
            ],
        ),
        migrations.AddField(
            model_name='job_role',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.sector'),
        ),
        migrations.AddField(
            model_name='job_category',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.sector'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.job_category')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.sector')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(to='jobsapp.skill'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=600, null=True, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.country')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsapp.state'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.state'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.work_mode'),
        ),
    ]
